# Generated by Django 2.0.5 on 2018-05-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180504_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='voting_open',
            new_name='is_accepting_votes',
        ),
    ]
