# Generated by Django 2.0.5 on 2018-05-04 02:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='extras',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
