# Generated by Django 2.0.5 on 2018-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_marks_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_accepting_entries',
            field=models.BooleanField(default=False),
        ),
    ]
