# Generated by Django 2.0.5 on 2018-05-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_is_accepting_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='voting_open',
            new_name='is_accepting_votes',
        ),
    ]
