# Generated by Django 2.0.4 on 2018-04-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='entryimage',
            options={'verbose_name_plural': 'entry images'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='repository',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entries.Entry'),
        ),
    ]
