# Generated by Django 2.0.4 on 2018-04-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20180421_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(default=None, upload_to='entries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(related_name='entries', to='categories.Category'),
        ),
    ]
