# Generated by Django 2.0.5 on 2018-05-04 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0003_auto_20180421_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.ManyToManyField(related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
