# Generated by Django 2.0.5 on 2018-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='team',
        ),
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
