# Generated by Django 2.0.5 on 2018-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20180504_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='team',
            field=models.CharField(blank=True, help_text='Comma-separated list of email addresses.', max_length=200),
        ),
    ]
