# Generated by Django 2.0.5 on 2018-05-05 08:09

from django.db import migrations, models
import hendoors.entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20180504_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(upload_to=hendoors.entries.models._generate_file_path),
        ),
    ]
